version: '3'
services:
  web:
    image: node:9.11.1
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file: ./.env-dev
    command: bash ./run.sh
    ports:
      - 5000:5000
    depends_on:
      - dynamodb
    links:
      - dynamodb:dynamodb

  builder:
    image: node:9.11.1
    command: bash ./run-build.sh
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - 8000:8000
