version: '3'
services:
  web:
    image: node:9.11.1
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file: ./.env-dev
    command: bash ./run.sh
    ports:
      - 5000:5000
    depends_on:
      - redis
    links:
      - redis:redis

  builder:
    image: node:9.11.1
    command: bash ./run-build.sh
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

  redis:
    image: redis:3.2.11-alpine
    ports:
      - 16379:6379
